---
# tasks file for roles/jenkins

- name: install rpm key
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install Jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: install packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Create Jenkins system group
  group:
    name: jenkins
    state: present
    system: yes

- name: Create Jenkins user
  user:
    name: jenkins
    home: /var/lib/jenkins
    system: yes
    shell: /bin/false
    group: jenkins

  # TODO: Add the henkins to the libvirt group!

- name: allowing firewall service rules
  firewalld:
    service: '{{ item }}'
    permanent: yes
    state: enabled
  notify:
    - restart firewalld
  with_items:
    - jenkins

- name: allowing firewall ports
  firewalld:
    port: "{{ jenkins_http_port }}/tcp"
    permanent: yes
    state: enabled
  notify:
    - restart firewalld

- name: Generate an Jenkins OpenSSH ECDSA keypair
  community.crypto.openssh_keypair:
    path: /var/lib/jenkins/.ssh
    comment: jenkins@workstation
    type: ecdsa
    size: 521
    force: yes
    state: present
    group: jenkins
    owner: jenkins
    mode: 0600
