---
# defaults file for install_matchbox

# https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.1/latest/

rhcos_baseurl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.2/latest
nightly_rhcos_baseurl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest

bios: rhcos-4.2.0-x86_64-metal-bios.raw.gz
kernel: rhcos-4.2.0-x86_64-installer-kernel
initramfs: rhcos-4.2.0-x86_64-installer-initramfs.img

nightly_bios: "rhcos-42.80.20191002.0-metal-bios.raw.gz"
nightly_kernel: "rhcos-42.80.20191002.0-installer-kernel"
nightly_initramfs: "rhcos-42.80.20191002.0-installer-initramfs.img"