---
# tasks file for roles/terraform

- name: download Terraform
  unarchive:
    src: "{{ terraform_url }}"
    dest: /tmp
    remote_src: yes

- name: copy Terraform binary
  become: yes
  copy:
    src: /tmp/terraform
    dest: /usr/local/bin
    mode: a+x
    remote_src: yes

- name: download Terraform Libvit provider
  unarchive:
    src: "{{ libvirt_provider_url }}"
    dest: /tmp
    remote_src: yes

- name: create Libvirt provider directory
  file:
    path: "~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/{{ libvirt_provider_version }}/linux_amd64"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'

- name: create plugins directory
  file:
    path: "/home/{{ become_user }}/.terraform.d/plugins"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'

- name: copy Terraform Libvirt Plugin binary into libvirt provider directory
  copy:
    src: /tmp/terraform-provider-libvirt
    dest: "~/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/{{ libvirt_provider_version }}/linux_amd64/"
    mode: a+x
    remote_src: yes

- name: copy Terraform Libvirt Plugin binary into plugins directory
  copy:
    src: /tmp/terraform-provider-libvirt
    dest: "/home/{{ become_user }}/.terraform.d/plugins"
    mode: a+x
    remote_src: yes

