---
# tasks file for install_haproxy

# TODO: Enable HAproxy service
- name: Install HAProxy
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Turn On packet forwarding in order HAProxy to start
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes

- name: Turn On Non-Local binding in order HAProxy to start
  become: true
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: "1"
    sysctl_set: yes

- name: allowing firewall rules for services
  become: true
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https

- name: allowing firewall rules for ports
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  notify: Restart firewalld
  loop:
    - 6443/tcp # HAProxy
    - 6443/udp
    - 19000/tcp # HAProxy stats page
    # - 22623/tcp # HAProxy
    # - 22623/udp

- name: Enable an SELinux boolean to allow HAProxy to bind to non standard ports (allow haproxy outgoing connections in SELinux)
  become: true
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Allow haproxy to bind to custom ports with SELinux
  become: true
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop:
    - 6443
    - 19000

# - name: Start HAProxy service
#   become: true
#   service:
#     name: haproxy
#     state: started
#     enabled: yes
