---
# tasks file for install_haproxy

- name: install
  import_tasks: install.yml
  tags:
    - haproxy:setup
    - haproxy:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - haproxy:setup
    - haproxy:setup:config

# - name: remove
#   import_tasks: remove.yml
#   tags:
#     - haproxy:remove
