---
# tasks file for roles/bastion

# - name: download ISO assets
#   get_url:
#     url: '{{ item }}'
#     dest: {{ cluster.libvirt.dir.iso }}
#     mode: '0644'
#   loop:
#     - "{{ fedora_server_baseurl }}/{{ fedora_server_iso }}"

- name: create images directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'
  loop:
    - "{{ libvirt_dir_iso }}"

- name: copy kickstart file to make it accessible
  become: true
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: qemu
    group: qemu
    mode: '0644'
  loop:
    - {src: 'kickstart.cfg.j2', dest: '/tmp/kickstart.cfg'}

- name: create Bastion VM
  command: >
    virt-install \
      --connect qemu:///system \
      --name {{ hostvars['bastion'].name }}.{{ cluster_name }}.{{ fqdn }} \
      --uuid {{ hostvars['bastion'].uuid }} \
      --description 'DHCP, DNS, HAProxy, TFTP, Matchbox' \
      --arch x86_64 \
      --os-type linux \
      --os-variant fedora{{ fedora_server_release }} \
      --cpu host \
      --vcpus {{ hostvars['bastion'].vcpu }} \
      --hvm \
      --memory {{ hostvars['bastion'].memory }} \
      --location {{ libvirt_dir_iso }}/{{ fedora_server_iso }} \
      --disk path={{ libvirt_dir_images }}/{{ hostvars['bastion'].name }}.{{ cluster_name }}.{{ fqdn }},size={{ hostvars['bastion'].disk.size }},cache=writeback,format={{ cluster.nodes['bastion'].disk.format }},io=threads,bus=virtio  \
      --autostart \
      --network bridge={{ cluster.nodes['bastion'].network.interface }},model=virtio,mac={{ cluster.nodes['bastion'].network.mac }} \
      --console pty,target_type=serial \
      --initrd-inject /tmp/kickstart.cfg \
      --extra-args \
        'inst.ks=file:/kickstart.cfg'


# 'inst.ks=file:/kickstart.cfg console=ttyS0,115200n8 serial'

# TODO: We need to wait while guest machine will boot up, because otherwise we will delete kickstart file too early.
# - name: delete kickstart.cfg
#   file:
#     state: absent
#     path: "/tmp/kickstart.cfg"
