---
# vars file for roles/nvidia

packages:
  - kernel-devel
  - kernel-headers
  - gcc
  - make
  - dkms
  - acpid
  - libglvnd-glx
  - libglvnd-opengl
  - libglvnd-devel
  - pkgconfig
  - vdpauinfo
  - libva-vdpau-driver
  - libva-utils

driver_version: "455.38"

