---
# tasks file for roles/vagrant

- name: download Hashicorp Vagrant
  unarchive:
    src: https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_linux_amd64.zip
    dest: /tmp
    remote_src: yes

- name: copy Vault binary
  become: yes
  copy:
    src: /tmp/vagrant
    dest: /usr/local/bin
    mode: a+x
    remote_src: yes
