---
# tasks file for roles/bazel

- name: install
  import_tasks: install.yml
  tags:
    - bazel:setup
    - bazel:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - bazel:setup
    - bazel:setup:config

# - name: remove
#   import_tasks: remove.yml
#   tags:
#     - bazel:remove
