---
# handlers file for roles/vault

- name: Restart Firewalld
  become: yes
  service:
    name: firewalld
    state: restarted

- name: Restart Vault
  become: yes
  service:
    name: vault
    state: restarted
