---
# tasks file for roles/common

- name: install rpm keys
  become: yes
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - http://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ fedora_distribution_version }}
    - http://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ fedora_distribution_version }}
    - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    - https://linux.teamviewer.com/pubkey/currentkey.asc
    - https://dl.google.com/linux/linux_signing_key.pub
    - https://slack.com/gpg/slack_pubkey_2019.gpg
    # - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    # - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: install the rpmfusion repo
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
    # disable_gpg_check: yes # TODO: I should add RPM Keys https://github.com/ansible/ansible/issues/71634#issuecomment-687202262
  loop:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm
    # - https://brave-browser-rpm-release.s3.brave.com/x86_64/
    # - https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

- name: install packages
  become: yes
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

