---
# vars file for roles/jenkins

packages:
  - jenkins
  - java-1.8.0-openjdk.x86_64

# jenkins_package_state: latest
# jenkins_hostname: https://jenkins.oswee.com
# jenkins_http_port: 9093
# jenkins_admin_username: '{{ vault_become_user }}'
# jenkins_admin_password: '{{ vault_become_pass }}'
# jenkins_plugins:
#   - blueocean
#   - name: greenballs
#     version: "1.15.1"
#   - name: terraform
#     version: "1.0.10"
#   - hashicorp-vault-plugin
#   - hashicorp-vault-pipeline
#   - solarized-theme
# jenkins_plugins_install_dependencies: true
# jenkins_plugins_state: latest
# java_packages:
#   - java-1.8.0-openjdk.x86_64
