---
  # tasks file for roles/nodejs

# TODO: https://stackoverflow.com/a/49844531/6651080
- name: install a modularity appstream with defined stream
  become: true
  shell: curl -sL https://rpm.nodesource.com/setup_15.x | sudo bash -
  args:
    warn: no

- name: Install NodeJS dependencies
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Install Yarn package globally
  become: yes
  npm:
    name: yarn@latest
    global: yes

- name: Install TypeScript package globally.
  yarn:
    name: typescript@latest
    global: yes

- name: Install Neovim package globally.
  yarn:
    name: neovim@latest
    global: yes

