---
  # tasks file for roles/code

- name: install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: install VS Code repo (dnf)
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: '{{ visual_studio_code_mirror }}/yumrepos/vscode'
    gpgkey: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    gpgcheck: yes

- name: install VS Code (dnf)
  become: yes
  dnf:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('-' + visual_studio_code_version, '') }}"
    state: present