---
  # tasks file for roles/ranger

- name: Install Ranger
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - ranger

- name: clone devicons plugin
  git:
    repo: https://github.com/alexanderjeurissen/ranger_devicons.git
    dest: $HOME/.config/ranger/plugins/ranger_devicons
    # version: master