---
  # tasks file for roles/ranger

- name: Copy default configs
  command: >
    ranger --copy-config=all

- name: Write config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ become_user }}"
    group: "{{ become_user_group }}"
    mode: "{{ item.mode }}"
    backup: yes
  loop:
  - { src: "rc.conf.j2", dest: "$HOME/.config/ranger/rc.conf", mode: '0644' }
