---
# tasks file for roles/nvidia

- name: unload nouveau
  become: true
  modprobe:
    name: nouveau
    state: absent
  ignore_errors: true

- name: blacklist nouveau
  become: true
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: blacklist nouveau
    state: present
    create: yes

- name: disable nonveau, opensource version of NVIDIA graphics driver
  become: true
  lineinfile:
    path: "/etc/sysconfig/grub"
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*rd.driver.blacklist\=nouveau)\"[^\"]+)(\".*)'
    line: '\1 rd.driver.blacklist=nouveau\2'
    state: present
    backup: yes

- name: update grub2 conf BIOS
  become: true
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: update grub2 conf UEFI
  become: true
  command: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg

- name: backup old initramfs nouveau image
  become: true
  copy:
    src: "/boot/initramfs-$(uname -r).img"
    dest: "/boot/initramfs-$(uname -r)-nouveau.img"
    remote_src: yes

- name: create new initramfs image
  become: true
  command: dracut /boot/initramfs-$(uname -r).img $(uname -r)
