---
# wireguard_address      : 10.8.0.2/24
# wireguard_endpoint     : ""
ansible_ssh_user       : dzintars
# ansible_become         : true
# ansible_become_method  : sudo
# ansible_become_user    : root
ansible_become_pass    : '{{ vault_ansible_become_pass }}'
ansible_ssh_user_pass  : '{{ vault_ansible_ssh_user_pass }}'
become_user            : dzintars
become_user_group      : dzintars
become_user_full_name  : Dzintars Klavins
become_user_email      : dzintars.klavins@gmail.com
ssh_key                : '{{ vault_ssh_key }}'
name                   : workstation
host                   : 2
libvirt_dir_iso        : $HOME/kvm/iso
libvirt_dir_images     : $HOME/kvm/images
disk_format            : qcow2
network_interface      : virbr0

