---
  # tasks file for roles/common
- name: create VS Code config directory
  file:
    path: "$HOME/.config/Code/User"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'

- name: copy configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "keybindings.json.j2", dest: "$HOME/.config/Code/User/keybindings.json", mode: '0644' }
    - { src: "settings.json.j2", dest: "$HOME/.config/Code/User/settings.json", mode: '0644' }

- name: increase file change watches
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    sysctl_set: yes
    state: present
    reload: yes
