---
# handlers file for roles/nvim

# - name: vim-plug install
#   command: >
#     nvim "+PlugInstall --sync" +qa

# - name: vim-plug install
#   # become: yes
#   ignore_errors: true
#   raw: nvim "+PlugInstall --sync" +qa &>/dev/null
#   changed_when: no

- name: vim-plug install
  shell: "nvim +Silent +VimEnter +{{ item }} +qall &>/dev/null"
  loop:
    - PlugInstall
    - PlugUpdate
    - PlugUpgrade
  become: false
