---
# tasks file for nvim

- name: Install Neovim
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - neovim
    - python3-neovim

# - name: Determine if vim plug is installed for neovim
#   stat:
#     path: "$HOME/.local/share/nvim/site/autoload/plug.vim"
#   register: vim_plug
#   ignore_errors: true

- name: Create vim plug directory
  # when: not vim_plug.stat.exists
  file:
    path: "$HOME/.local/share/nvim/site/autoload"
    state: directory
    # owner: "{{ become_user }}"

- name: Install vim plug
  # when: not vim_plug.stat.exists
  # become: yes
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "$HOME/.local/share/nvim/site/autoload/"
    # owner: "{{ become_user }}"
    force: yes

- name: Install Neovim package globally.
  yarn:
    name: neovim@latest
    global: yes
    
- name: Install pynvim python package
  pip:
    name: pynvim
    state: forcereinstall

