---
# tasks file for roles/nvim


- name: Build NeoVim
  import_tasks: build.yml
  tags:
    - nvim:setup
    - nvim:setup:build

#- name: Install NeoVim
#  import_tasks: install.yml
#  tags:
#    - nvim:setup
#    - nvim:setup:install

#- name: Update configuration
#  import_tasks: configure.yml
#  tags:
#    - nvim:setup
#    - nvim:setup:config

#- name: Remove Neovim
#  import_tasks: remove.yml
#  tags:
#    - nvim:remove
