---
# tasks file for roles/nvim


- name: Build NeoVim
  import_tasks: build.yml
  tags:
    - nvim:setup
    - nvim:setup:build

- name: Setup Vim Plug
  import_tasks: vim-plug.yml
  tags:
    - nvim:setup
    - nvim:setup:vimplug

- name: Setup Install packages
  import_tasks: packages.yml
  tags:
    - nvim:setup
    - nvim:setup:packages

- name: Update configuration
  import_tasks: configure.yml
  tags:
    - nvim:setup
    - nvim:setup:config

#- name: Remove Neovim
#  import_tasks: remove.yml
#  tags:
#    - nvim:remove
