---
# tasks file for install_dhcp

- name: deploy dhcpd.conf template
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart dhcpd