---
# tasks file for roles/swaylock-effects

- name: Install prerequisites
  become: yes
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    "{{ requirements }}"

- name: Get package facts
  ansible.builtin.package_facts:
    manager: rpm

- name: Remove default swaylock-effects package if exists
  become: yes
  ansible.builtin.dnf:
    name: swaylock-effects
    state: absent
  when: "'swaylock-effects' in ansible_facts.packages"

- name: Clone swaylock-effects repository
  ansible.builtin.git:
    repo: https://github.com/mortie/swaylock-effects.git
    dest: "/home/{{ become_user }}/code/github.com/mortie/swaylock-effects/"
    version: master
    depth: 1
  register: swaylock_effects_repo

- name: Cleanup build artifacts
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ become_user }}/code/github.com/mortie/swaylock-effects/.deps"
    - "/home/{{ become_user }}/code/github.com/mortie/swaylock-effects/build"
  when: swaylock_effects_repo.changed

- name: meson build swaylock-effects
  command: meson --prefix=/usr build/
  args:
    chdir: "/home/{{ become_user }}/code/github.com/mortie/swaylock-effects"
  when: swaylock_effects_repo.changed

- name: build swaylock-effects
  command: ninja -C build
  args:
    chdir: "/home/{{ become_user }}/code/github.com/mortie/swaylock-effects"
  when: swaylock_effects_repo.changed

- name: install swaylock-effects
  become: yes
  command: ninja -C build install
  args:
    chdir: "/home/{{ become_user }}/code/github.com/mortie/swaylock-effects"
  when: swaylock_effects_repo.changed

- name: Change swaylock binary permissions
  become: yes
  ansible.builtin.file:
    path: /usr/bin/swaylock
    mode: 'a+s'
