---
# tasks file for roles/go

- name: install
  import_tasks: install.yml
  tags:
    - go:setup
    - go:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - go:setup
    - go:setup:config

# - name: remove
#   import_tasks: remove.yml
#   tags:
#     - go:remove
