---
# tasks file for roles/mariadb

- name: install mariadb
  import_tasks: install.yml
  tags:
    - mariadb:setup
    - mariadb:setup:install

- name: configure mariadb
  import_tasks: configure.yml
  tags:
    - mariadb:setup
    - mariadb:setup:config

- name: mariadb secure install
  import_tasks: secure-installation.yml
  tags:
    - mariadb:setup
    - mariadb:setup:secinst

- name: mariadb database setup
  import_tasks: databases.yml
  tags:
    - mariadb:setup
    - mariadb:setup:databases

- name: mariadb user setup
  import_tasks: users.yml
  tags:
    - mariadb:setup
    - mariadb:setup:users

- name: remove mariadb
  import_tasks: remove.yml
  tags:
    - mariadb:remove
