---
# tasks file for roles/polybar

- name: install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

# - name: clone polybar repository into /tmp.
#   git:
#     repo: https://github.com/polybar/polybar
#     version: master
#     dest: /tmp/polybar

# In order to fix `journalctl -b`'s `polybar|warn:  Dropping unmatched character  (U+e016)` errors i need to install Siji font
- name: clone Siji font
  git:
    repo: https://github.com/stark/siji.git
    dest: /tmp/siji
    version: master

- name: Install Siji font
  command: >
    ./install.sh -d $HOME/.fonts
  args:
    chdir: /tmp/siji
