---
# tasks file for roles/vagrant

- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    "{{ packages }}"

- name: Install Vagrant
  dnf:
    name: "{{ vagrant_rpm }}"
    state: latest
    disable_gpg_check: yes

# - name: Download Hashicorp Vagrant
#   unarchive:
#     src: "{{ vagrant_archive }}"
#     dest: /tmp
#     remote_src: yes

# - name: Copy Vagrant binary
#   copy:
#     src: /tmp/vagrant
#     dest: /usr/local/bin
#     mode: a+x
#     remote_src: yes

- name: Install Vagrant-Libvirt plugin
  command: vagrant plugin install vagrant-libvirt
  environment:
    CONFIGURE_ARGS: "{{ with_libvirt_include }} {{ with_libvirt_lib }}"
