---
# handlers file for install_named

- name: enable and start named
  systemd:
    name: named-chroot
    enabled: yes
    state: started

- name: restart named
  systemd:
    state: restarted
    daemon_reload: yes
    name: named-chroot

- name: restart firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld

- name: restart NetworkManager
  systemd:
    state: restarted
    daemon_reload: yes
    name: NetworkManager