---
# handlers file for install_named

- name: enable named
  systemd:
    name: named-chroot
    enabled: yes

- name: start named
  systemd:
    name: named-chroot
    state: started

- name: restart named
  systemd:
    state: restarted
    daemon_reload: yes
    name: named-chroot

- name: restart firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld

- name: restart NetworkManager
  systemd:
    state: restarted
    daemon_reload: yes
    name: NetworkManager
