---
# vars file for roles/sway

packages:
  - sway
  - waybar
  # - swaylock
  - swaylock-effects
  - swayidle
  - mako
  - wofi
  - wl-clipboard
  - slurp
  - grim
  - swappy
  - breeze-cursor-theme
  - breeze-icon-theme


mountpoints:
  - /mnt/external
  - /mnt/backups
  - /mnt/nextcloud
