---
- name: Install and configure OpenShift Bastion server
  hosts: BASTION
  gather_facts: yes
  # become: true
  # become_user: dzintars
  # become_method: sudo

  # vars_prompt:
  # - name: cluster.fqdn
  #   prompt: 'Cluster FQDN? e.g. "example.com"'
  #   private: no

  roles:
    # - role: debug
    #   tags: [debug]
    - role: named
      tags: [named]
      become: true
    - role: bertvv.tftp
      tags: [tftp]
      become: true
    - role: setup_firewalld
      tags: [firewalld]
    # - role: setup_selinux
    #   tags: [selinux]
    # - role: install_dhcp
    #   tags: [dhcpd]
    #   become: true
    # - role: install_haproxy
    #   tags: [haproxy]
    # - role: install_ipxe
    #   tags: [ipxe]
    #   become: true
    # - role: install_matchbox
    #   tags: [matchbox]
    #   become: true
    # - role: deploy_ignition
    #   tags: [ignition]
    #   become: true

    # - role: provision_tls
    # - role: install_tftp