---
- name: Bootstrap workstation
  hosts: WORKSTATION
  connection: local
  gather_facts: yes
  # become: yes
  # become_user: dzintars
  # become_method: sudo

  roles:
    - role: deploy_bastion
      tags: [bastion]
      become: false
    - role: network
      tags: [network]
    - role: openshift
      tags: [openshift]
    - role: libvirt
      tags: [libvirt]
      # become: true
    - role: protoc
      tags: [protoc]
      become: true
    - role: haproxy
      tags: [haproxy]
      # become: true
    - role: certbot
      tags: [certbot]
      # become: true
    - role: nvim
      tags: [nvim]
    - role: nvidia
      tags: [nvidia]
    - role: nodejs
      tags: [nodejs]
    - role: ranger
      tags: [ranger]
    - role: alacritty
      tags: [alacritty]
    - role: lightdm
      tags: [lightdm]
    - role: i3wm
      tags: [i3wm]
    - role: git
      tags: [git]
    - role: vault
      tags: [vault]
    - role: mariadb
      tags: [mariadb]
    - role: xorg
      tags: [xorg]
    - role: polybar
      tags: [polybar]
    - role: zsh
      tags: [zsh]
    - role: dzintars.podman
      tags: [podman]
    - role: containers
      tags: [containers]
    - role: code
      tags: [code]
    - role: common
      tags: [common]
    - role: tmux
      tags: [tmux]
    - role: pulseaudio
      tags: [pulseaudio]
    - role: ansible
      tags: [ansible]
