---
# tasks file for roles/certbot

# - name: mount backups drive
#   become: yes
#   mount:
#     path: /mnt/backups
#     src: UUID=478ebb49-bd04-4f34-b459-791638b9bec4 # /dev/sdb
#     fstype: btrfs
#     opts: bind
#     state: present

# - name: mount and bind a backups volume
#   become: true
#   mount:
#     path: /mnt/backups
#     src: /dev/sdb
#     opts: bind
#     state: mounted
#     fstype: btrfs

- name: copy existing certificates
  become: yes
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: no
    group: no
  delegate_to: '192.168.1.2'
  loop:
    - { src: "/mnt/backups/fedora/32/etc/letsencrypt/", dest: "/etc/letsencrypt" }

- name: copy existing certificates into userspace
  become: yes
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: yes
    group: yes
  delegate_to: '192.168.1.2'
  loop:
    - { src: "/mnt/backups/fedora/32/home/dzintars/.tls/", dest: "/home/dzintars/.tls" }
