---
  # tasks file for roles/i3wm

- name: install packages
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: remove i3status
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - i3status