---
# tasks file for roles/git

- name: install
  import_tasks: install.yml
  tags:
    - git:setup
    - git:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - git:setup
    - git:setup:config

- name: remove
  import_tasks: remove.yml
  tags:
    - git:remove