---
# tasks file for roles/setup_selinux

- name: install dependencies
  import_tasks: install.yml
  tags:
    - selinux:install

- name: update configuration
  import_tasks: configure.yml
  tags:
    - selinux:config