---
# Tasks file to create Storage Pool and Domains

- name: Stop and remove existing domains by their name (All VMs)
  import_tasks: undefine_domains.yml
  tags:
  - openshift:cleanup

- name: Undefine Storage Pool
  import_tasks: undefine_storage_pool.yml
  tags:
  - openshift:cleanup

- name: Create and start Storage Pool
  import_tasks: create_storage_pool.yml
  tags:
  - openshift:provision

# - name: Create volumes
#   import_tasks: create_volumes.yml
#   tags:
#   - setup

# - name: Create and start domains (All VMs)
#   import_tasks: create_domains.yml
#   tags:
#   - setup

- name: Create and start domains (All Guest VMs)
  import_tasks: virt_install.yml
  tags:
  - openshift:provision
