---
  # tasks file for roles/nodejs

# TODO: https://stackoverflow.com/a/49844531/6651080
- name: install a modularity appstream with defined stream
  become: true
  shell: curl -sL https://rpm.nodesource.com/setup_15.x | sudo bash -
  args:
    warn: no

- name: Install NodeJS dependencies
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

#- name: Install TypeScript package globally
#  yarn:
#    name: typescript@latest
#    global: yes

# TODO: Extend $PATH ENV variable with export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
