---

- name: delete all connections
  command: >
    for i in `nmcli c | \
    grep -o -- "[0-9a-fA-F]\{8\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{12\}"`; \
    do nmcli connection delete uuid $i; \
    done

- name: delete all network devices
  command: >
    for i in `nmcli d | \
    grep -o -- "[0-9a-fA-F]\{8\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{4\}-[0-9a-fA-F]\{12\}"`; \
    do nmcli device delete uuid $i; \
    done
