---
# tasks file for named

- name: install named
  import_tasks: install.yml
  tags:
  - named:install

- name: update named configuration
  import_tasks: configure.yml
  tags:
  - named:config

- name: start named
  import_tasks: start.yml
  tags:
  - named:start

# - name: remove named
#   import_tasks: remove.yml
#   tags:
#   - named:remove