---
# tasks file for roles/vault

- name: create vault directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: vault
    group: vault
    mode: '0755'
  loop:
    - /etc/vault.d
    - /opt/vault/data
    - /opt/vault/tls

- name: Copy Vault configuration file
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: vault
    group: vault
    # setype: named_conf_t
    mode: '0640'
  loop:
    - { src: "vault.hcl.j2", dest: "/etc/vault.d/vault.hcl" }

- name: copy TLS certificates
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: vault
    group: vault
    remote_src: yes
  loop:
    - { src: "/etc/letsencrypt/live/{{ fqdn }}/fullchain.pem", dest: "/opt/vault/tls" }
    - { src: "/etc/letsencrypt/live/{{ fqdn }}/privkey.pem", dest: "/opt/vault/tls" }

- name: Make sure a vault.service is enabled and running
  become: yes
  systemd:
    name: vault
    enabled: yes
    state: started

