---
# tasks file for roles/vault

- name: install Hashicorp Vault
  import_tasks: install.yml
  tags:
    - vault:setup
    - vault:setup:install

- name: configure vault
  import_tasks: configure.yml
  tags:
    - vault:setup
    - vault:setup:config
