---
# tasks file for roles/containers

- name: install
  import_tasks: install.yml
  tags:
    - containers:setup
    - containers:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - containers:setup
    - containers:setup:config

- name: remove
  import_tasks: remove.yml
  tags:
    - containers:remove