---
# installation tasks file for roles/libvirt

- name: install libvirt dependencies
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

# Create libvirt group and add current user to it to allow to run libvirt without root

# TODO: Some of these tasks changes home directory group to libvirt
- name: create libvirt system group
  become: true
  group:
    name: libvirt
    state: present
    system: yes

- name: add {{ become_user }} to libvirt group
  become: true
  user:
    name: "{{ become_user }}"
    groups:
      - libvirt
    append: yes
    state: present

- name: just force systemd to re-execute itself (2.8 and above)
  become: true
  systemd:
    daemon_reexec: yes

# id $(whoami)

# Start and enable libvirtd

- name: start libvirtd service
  become: true
  service:
    name: libvirtd
    state: started
    enabled: yes
