---
# tasks file for roles/libvirt

- name: install
  import_tasks: install.yml
  tags:
    - libvirt:setup
    - libvirt:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - libvirt:setup
    - libvirt:setup:config

- name: remove
  import_tasks: remove.yml
  tags:
    - libvirt:remove