---
# tasks file for install_haproxy

- name: copy haproxy.cfg and reload HAProxy
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    # setype: named_conf_t
    mode: 0644
  loop:
    - {src: 'haproxy.cfg.j2', dest: '/etc/haproxy/haproxy.cfg'}
  notify: Restart HAProxy