# roles/tftp/vars/CentOS.yml
# Variables specific to the CentOS distribution
---

tftp_packages:
  - libsemanage-python
  - tftp-server

tftp_service: tftp.socket

tftp_server: /usr/sbin/in.tftpd
tftp_config: /usr/lib/systemd/system/tftp.service

tftp_foreman_map_file: /etc/tftpd.map
