---
  # tasks file for roles/i3wm

- name: create mounting directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'
  loop: "{{ mountpoints }}"

- name: copy configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "config.j2", dest: "$HOME/.config/i3/config", mode: '0644' }
    - { src: "compton.conf.j2", dest: "$HOME/.config/compton.conf", mode: '0644' }
    - { src: ".profile.j2", dest: "$HOME/.profile", mode: '0644' }
    - { src: ".fehbg.j2", dest: "$HOME", mode: '0644'  }
    - { src: "lock_and_blur.sh.j2", dest: "$HOME/.config/lock_and_blur.sh", mode: '0755' }

# - name: create fonts directory
#   file:
#     path: "$HOME/.fonts"
#     state: directory
#     owner: "{{ become_user }}"
#     group: "{{ become_user }}"
#     mode: '0755'

- name: copy fonts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "fonts/", dest: "$HOME/.fonts/", mode: '0755' }

- name: create wallpapers directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'
  loop:
    - "$HOME/Pictures/Wallpapers"

- name: copy background images
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0644'
  loop:
    - { src: "tharsus.jpg", dest: "$HOME/Pictures/Wallpapers" }