---
  # tasks file for roles/yarn

- name: copy template/s
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: ".tmux.conf.j2", dest: "$HOME/.tmux.conf" }