---
- name: Bootstrap workstation
  hosts: WORKSTATION
  connection: local
  gather_facts: yes
  become: no
  # become_user: dzintars
  # become_method: sudo

  roles:
    - role: bastion
      tags: [bastion]
    - role: network
      tags: [network]
    - role: bazel
      tags: [bazel]
    - role: espanso
      tags: [espanso]
    - role: openshift
      tags: [openshift]
    - role: go
      tags: [go]
    - role: protoc
      tags: [protoc]
    # - role: haproxy
    #   tags: [haproxy]
    - role: certbot
      tags: [certbot]
    - role: nvim
      tags: [nvim]
    - role: nvidia
      tags: [nvidia]
    - role: nodejs
      tags: [nodejs]
    - role: ranger
      tags: [ranger]
    - role: alacritty
      tags: [alacritty]
    - role: lightdm
      tags: [lightdm]
    - role: i3wm
      tags: [i3wm]
    - role: git
      tags: [git]
    # - role: vault
    #   tags: [vault]
    # - role: mariadb
    #   tags: [mariadb]
    # - role: geerlingguy.mysql
    #   become: yes
    #   tags: [mariadb]
    - role: xorg
      tags: [xorg]
    - role: polybar
      tags: [polybar]
    - role: zsh
      tags: [zsh]
    - role: dzintars.podman
      tags: [podman]
    - role: containers
      tags: [containers]
    - role: code
      tags: [code]
    - role: common
      tags: [common]
    - role: tmux
      tags: [tmux]
    - role: pulseaudio
      tags: [pulseaudio]
    - role: ansible
      tags: [ansible]
    - role: obsidian
      tags: [obsidian]
    - role: sway
      tags: [sway]
    - role: minecraft
      tags: [minecraft]
    - role: terraform
      tags: [terraform]
    - role: spire
      tags: [spire]
    # - role: minio
    #   tags: [minio]
    # - role: jenkins
    #   tags: [jenkins]
