---

# TODO: Download assets

- name: copy kickstart file
  become: true
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: qemu
    group: qemu
    mode: '0644'
  loop:
    - {src: 'kickstart.cfg.j2', dest: '/var/lib/libvirt/kickstart.cfg'}

- name: create Bastion VM
  command: >
    virt-install \
      --connect qemu:///system \
      --name {{ cluster.nodes['bastion'].name }}.{{ cluster.name }}.{{ cluster.fqdn }} \
      --description 'DHCP, DNS, HAProxy, TFTP, Matchbox' \
      --vcpus {{ cluster.nodes['bastion'].vcpu }} \
      --hvm \
      --memory {{ cluster.nodes['bastion'].memory }} \
      --location $HOME/kvm/iso/Fedora-Server-dvd-x86_64-30-1.2.iso \
      --disk path=$HOME/kvm/pools/bastion/{{ cluster.nodes['bastion'].name }}.{{ cluster.name }}.{{ cluster.fqdn }},size={{ cluster.nodes['bastion'].disk.size }},cache=writeback,format={{ cluster.nodes['bastion'].disk.format }},io=threads,bus=virtio  \
      --accelerate \
      --os-type linux \
      --os-variant fedora30 \
      --network bridge={{ cluster.nodes['bastion'].network.name }},model=virtio \
      --initrd-inject /var/lib/libvirt/kickstart.cfg \
      -x "ks=file:/kickstart.cfg" \
      --console pty,target_type=serial
      
      

# TODO: We need to wait while guest machine will boot up, because otherwise we will delete kickstart file too early.
# - name: delete kickstart.cfg
#   file:
#     state: absent
#     path: "/var/lib/libvirt/kickstart.cfg"