---
# tasks file for install_named

- name: install dependencies
  become: true
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - bind-chroot

- name: add DNS service to firewall
  become: true
  firewalld:
    service: dns
    permanent: yes
    state: enabled
  notify:
    - restart firewalld
    - start named-chroot