---
# tasks file for roles/podman

- name: create containers config directory
  file:
    path: "$HOME/.config/containers"
    state: directory
    owner: "{{ become_user }}"
    group: "{{ become_user }}"
    mode: '0755'

- name: copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "containers.conf", dest: "$HOME/.config/containers/", mode: '0644' }
    - { src: "registries.conf", dest: "$HOME/.config/containers/", mode: '0644' }
    - { src: "storage.conf", dest: "$HOME/.config/containers/", mode: '0644' }
    - { src: "auth.json", dest: "$HOME/.config/containers/", mode: '0644' }

- name: add docker alias to zshrc
  lineinfile:
    path: $HOME/.zshrc
    line: "alias docker='podman'"
    owner: "{{ become_user }}"
    regexp: "^alias docker='podman'$"
    state: present
    insertafter: '^# Aliases'
    # create: True
