---
# tasks file for roles/common

- name: install
  import_tasks: install.yml
  tags:
    - common:setup
    - common:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - common:setup
    - common:setup:config

# - name: remove
#   import_tasks: remove.yml
#   tags:
#     - common:remove
