---
# tasks file for roles/debug

# - name: debug message 1
#   debug:
#     msg: System debug message - {{ cluster.fqdn }}

# - name: debug message 2
#   debug:
#     msg: Promp value - {{ cluster.fqdn }}

- name: find interface facts
  debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_%s' | format(item)] }}"
  with_items: "{{ ansible_interfaces }}"

# - name: Copy tests files
#   template:
#     src: '{{ item.src }}'
#     dest: '{{ item.dest }}'
#     mode: '0644'
#   loop:
#     - {src: 'test.txt.j2', dest: '/home/dzintars/debug-test.txt'}