---
# tasks file for roles/bazel

- name: add bazel alias
  lineinfile:
    path: $HOME/.zshrc
    line: "alias bazel='bazelisk'"
    owner: "{{ become_user }}"
    regexp: "^alias bazel='bazelisk'$"
    state: present
    insertafter: '^# Aliases'
    # create: True
