---
# tasks file for roles/bazel

- name: download bazelisk
  become: yes
  get_url:
    url: https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64
    dest: /usr/local/bin/bazelisk
    mode: a+x

# - name: clone bazel-watcher
#   # become: yes
#   git:
#     repo: git@github.com:bazelbuild/bazel-watcher
#     dest: /tmp/bazel-watcher
#     version: master

# - name: build ibazel
#   become: yes
#   command:
#     argv:
#       - bazel
#       - build
#       - //ibazel
#     chdir: /tmp/bazel-watcher/
#     creates: /tmp/bazel-watcher/bazel-bin/ibazel/linux_amd64_pure_stripped

- name: download ibazel
  become: yes
  get_url:
    url: https://github.com/bazelbuild/bazel-watcher/releases/download/v0.14.0/ibazel_linux_amd64
    dest: /usr/local/bin/ibazel
    mode: a+x

- name: download buildifier
  become: yes
  get_url:
    url: https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildifier
    dest: /usr/local/bin/buildifier
    mode: a+x
