---
# tasks file for install_dhcp

- name: deploy dhcpd.conf template
  become: yes
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart dhcpd

- name: allowing firewall rules for ports
  become: true
  firewalld:
    port: '{{ item }}'
    permanent: yes
    state: enabled
  notify: restart firewalld
  loop:
    - 67/udp      # bootp & DHCP

- name: add DHCP service to firewall
  become: yes
  firewalld:
    service: dhcp
    permanent: yes
    state: enabled
  notify: restart firewalld

- name: start DHCP service
  become: yes
  systemd:
    name: dhcpd
    state: started
    enabled: yes

