---
# tasks file for roles/dhcpd

- name: Install DHCP
  import_tasks: install.yml
  tags:
    - dhcpd:setup
    - dhcpd:setup:install

- name: Update configuration
  import_tasks: configure.yml
  tags:
    - dhcpd:setup
    - dhcpd:setup:config

