---
# tasks file for ipxe

- name: Install iPXE
  become: yes
  dnf:
    name: '{{ item }}'
    state: latest
  loop:
    - ipxe-bootimgs

# - name: Link the image
#   file:
#     src: /usr/share/ipxe/undionly.kpxe
#     dest: /var/lib/tftpboot
#     force: yes
#     state: link

- name: Copy undionly.kpxe chainboot
  become: yes
  copy:
    src: /usr/share/ipxe/undionly.kpxe
    dest: /var/lib/tftpboot/undionly.kpxe
    # owner: root
    # group: root
    mode: "0644"
    remote_src: yes

- name: Start TFTP service
  become: yes
  service:
    name: tftp
    state: started
    enabled: yes
