---
# tasks file for roles/sway

- name: install
  import_tasks: install.yml
  tags:
    - sway:setup
    - sway:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - sway:setup
    - sway:setup:config

# - name: remove
#   import_tasks: remove.yml
#   tags:
#     - sway:remove
