---
# tasks file for create_ocp_libvirt_cluster

- name: Destroy all {{ cluster.name }} domains
  virt:
    name: '{{ node.value.name }}.{{ cluster.name }}.{{ cluster.fqdn }}'
    command: destroy
    uri: 'qemu:///system'
  loop: "{{ lookup('dict', cluster.nodes) }}"
  loop_control:
    loop_var: node

- name: Udefine all {{ cluster.name }} domains
  virt:
    name: '{{ node.value.name }}.{{ cluster.name }}.{{ cluster.fqdn }}'
    command: undefine
    uri: 'qemu:///system'
  loop: "{{ lookup('dict', cluster.nodes) }}"
  loop_control:
    loop_var: node