---
# tasks file for roles/named

- name: install
  import_tasks: install.yml
  tags:
    - named:setup
    - named:setup:install

- name: configure
  import_tasks: configure.yml
  become: yes
  tags:
    - named:setup
    - named:setup:config

- name: start
  import_tasks: start.yml
  become: yes
  tags:
    - named:setup
    - named:setup:start

# - name: remove named
#   import_tasks: remove.yml
#   tags:
#   - named:remove
