---
# tasks file for roles/certbot

- name: install
  import_tasks: install.yml
  tags:
    - certbot:setup
    - certbot:setup:install

- name: config
  import_tasks: configure.yml
  tags:
    - certbot:setup
    - certbot:setup:config

- name: remove
  import_tasks: remove.yml
  tags:
    - certbot:remove