---
  # tasks file for nvim

- name: Create nvim directory.
  # when: not vim_plug.stat.exists
  # become: yes
  file:
    path: "$HOME/.config/nvim"
    state: directory
    # owner: "{{ become_user }}"

- name: Create Neovim directories.
  # when: not vim_plug.stat.exists
  # become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    # owner: "{{ become_user }}"
  loop:
    - "$HOME/.config/nvim/autoload"
    - "$HOME/.config/nvim/plugins.d"
    - "$HOME/.config/nvim/plugged"
    - "$HOME/.config/nvim/sessions"
    - "$HOME/.config/nvim/undodir"

- name: Copy init.vim
  # become: false
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "autoload/plug.vim.j2", dest: "$HOME/.config/nvim/autoload/plug.vim" }
    - { src: "plugins.d/01-startify.vim.j2", dest: "$HOME/.config/nvim/plugins.d/01-startify.vim" }
    - { src: "plugins.d/02-airline.vim.j2", dest: "$HOME/.config/nvim/plugins.d/02-airline.vim" }
    - { src: "plugins.d/20-coc.vim.j2", dest: "$HOME/.config/nvim/plugins.d/20-coc.vim" }
    - { src: "plugins.d/40-nerdtree.vim.j2", dest: "$HOME/.config/nvim/plugins.d/40-nerdtree.vim" }
    - { src: "plugins.d/50-fzf.vim.j2", dest: "$HOME/.config/nvim/plugins.d/50-fzf.vim" }
    - { src: "autocmd.vim.j2", dest: "$HOME/.config/nvim/autocmd.vim" }
    - { src: "coc-settings.json.j2", dest: "$HOME/.config/nvim/coc-settings.json" }
    - { src: "funcs.vim.j2", dest: "$HOME/.config/nvim/funcs.vim" }
    - { src: "general.vim.j2", dest: "$HOME/.config/nvim/general.vim" }
    - { src: "init.vim.j2", dest: "$HOME/.config/nvim/init.vim" }
    - { src: "keys.vim.j2", dest: "$HOME/.config/nvim/keys.vim" }
    - { src: "plugins.vim.j2", dest: "$HOME/.config/nvim/plugins.vim" }
    - { src: "settings.vim.j2", dest: "$HOME/.config/nvim/settings.vim" }
    - { src: "theme.vim.j2", dest: "$HOME/.config/nvim/theme.vim" }
  notify: Install plugins

# # Update remote plugins (e.g., deoplete).
# - name: Update remote plugins
#   # become: yes
#   ignore_errors: true
#   raw: nvim "+UpdateRemotePlugins --sync" +qa &>/dev/null
#   changed_when: no